### ISSUE TITLE
error in running ALBERT create_pretraining_data.py

### ISSUE THREAD

**Issue by aravindchaluvadi** [LydiaXiaohongLi/Albert_Finetune_with_Pretrain_on_Custom_Corpus#1]
I am facing the below issue while running the command for creating data for inputing to the albert model.

```

python create_pretraining_data.py --input_file /media/xxxx/NewVolume/Albert_Finetune_with_Pretrain_on_Custom_Corpus/data_toy/restaurant_review_train --output_file /media/xxxx/NewVolume/ALBERT/ouput --vocab_file /media/xxxx/NewVolume/Albert_Finetune_with_Pretrain_on_Custom_Corpus/models_toy/vocab.txt
WARNING:tensorflow:From create_pretraining_data.py:653: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.

WARNING:tensorflow:From create_pretraining_data.py:618: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

W0114 11:29:58.957636 140552204957504 module_wrapper.py:139] From create_pretraining_data.py:618: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

WARNING:tensorflow:From create_pretraining_data.py:618: The name tf.logging.INFO is deprecated. Please use tf.compat.v1.logging.INFO instead.

W0114 11:29:58.957761 140552204957504 module_wrapper.py:139] From create_pretraining_data.py:618: The name tf.logging.INFO is deprecated. Please use tf.compat.v1.logging.INFO instead.

WARNING:tensorflow:From create_pretraining_data.py:626: The name tf.gfile.Glob is deprecated. Please use tf.io.gfile.glob instead.

W0114 11:29:58.958572 140552204957504 module_wrapper.py:139] From create_pretraining_data.py:626: The name tf.gfile.Glob is deprecated. Please use tf.io.gfile.glob instead.

WARNING:tensorflow:From create_pretraining_data.py:628: The name tf.logging.info is deprecated. Please use tf.compat.v1.logging.info instead.

W0114 11:29:58.959418 140552204957504 module_wrapper.py:139] From create_pretraining_data.py:628: The name tf.logging.info is deprecated. Please use tf.compat.v1.logging.info instead.

INFO:tensorflow:*** Reading from input files ***
I0114 11:29:58.959500 140552204957504 create_pretraining_data.py:628] *** Reading from input files ***
INFO:tensorflow:  /media/xxxx/NewVolume/Albert_Finetune_with_Pretrain_on_Custom_Corpus/data_toy/restaurant_review_train
I0114 11:29:58.959625 140552204957504 create_pretraining_data.py:630]   /media/xxxx/NewVolume/Albert_Finetune_with_Pretrain_on_Custom_Corpus/data_toy/restaurant_review_train
WARNING:tensorflow:From create_pretraining_data.py:228: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

W0114 11:29:58.960052 140552204957504 module_wrapper.py:139] From create_pretraining_data.py:228: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

Traceback (most recent call last):
  File "create_pretraining_data.py", line 653, in <module>
    tf.app.run()
  File "/home/xxxx/.local/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/xxxx/.local/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/xxxx/.local/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "create_pretraining_data.py", line 636, in main
    rng)
  File "create_pretraining_data.py", line 230, in create_training_instances
    line = reader.readline()
  File "/home/xxxx/.local/lib/python3.6/site-packages/tensorflow_core/python/lib/io/file_io.py", line 179, in readline
    return self._prepare_value(self._read_buf.ReadLineAsString())
  File "/home/xxxx/.local/lib/python3.6/site-packages/tensorflow_core/python/lib/io/file_io.py", line 98, in _prepare_value
    return compat.as_str_any(val)
  File "/home/xxxx/.local/lib/python3.6/site-packages/tensorflow_core/python/util/compat.py", line 123, in as_str_any
    return as_str(value)
  File "/home/xxxx/.local/lib/python3.6/site-packages/tensorflow_core/python/util/compat.py", line 93, in as_text
    return bytes_or_text.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb9 in position 8: invalid start byte

```

@LydiaXiaohongLi

**Comment by LydiaXiaohongLi** [comment]
Hi,
For the create_pretraining_data.py script, you should use the original text corpus file (I didnt upload the file to repo, it should be the restaurant_review_nopunct.txt with punctuation). restaurant_review_train is the output from this step. I have a medium article: https://towardsdatascience.com/fine-tune-albert-with-pre-training-on-custom-corpus-f56ea3cfdc82 on this topic with more details. 
Thanks
Regards
Xiaohong

**Comment by aravindchaluvadi** [comment]
Yes I have successfully able to execute the above command and then when i run the 
`
python run_pretraining.py --input_file=/media/xxxx/NewVolume/ALBERT/ouput.txt --output_dir=/media/xxxx/NewVolume/Albert_Finetune_with_Pretrain_on_Custom_Corpus/models_toy --albert_config_file=/media/xxxx/NewVolume/Albert_Finetune_with_Pretrain_on_Custom_Corpus/models_toy/albert_config.json python run_pretraining.py -- train_batch_size=2 --num_warmup_steps=100 --num_train_steps=300 --max_seq_length=64`


I am getting an OOM error as even though I have a GPU of 1660ti with 4gb  and 16 gb RAM with 6 core processor

@LydiaXiaohongLi

**Comment by aravindchaluvadi** [comment]
I am able to successfully run the above command after which when ui run the run_pretraining.py i am getting the below error can someone explain me what is this related to :

This is the command that I am executing foe the below step:

`python run_pretraining.py --input_file=/media/xxxx/NewVolume/ALBERT/ouput.txt --output_dir=/media/xxxx/NewVolume/Albert_Finetune_with_Pretrain_on_Custom_Corpus/models_toy --albert_config_file=/media/xxxx/NewVolume/Albert_Finetune_with_Pretrain_on_Custom_Corpus/models_toy/albert_config.json --train_batch_size=1 --num_warmup_steps=10 --num_train_steps=30 --max_seq_length=64
`
```
ERROR:tensorflow:Error recorded from training_loop: 2 root error(s) found.
  (0) Invalid argument: {{function_node tf_data_experimental_map_and_batch_<lambda>_54}} Key: segment_ids.  Can't parse serialized Example.
	 [[{{node ParseSingleExample/ParseSingleExample}}]]
	 [[IteratorGetNext]]
	 [[IteratorGetNext/_795]]
  (1) Invalid argument: {{function_node tf_data_experimental_map_and_batch_<lambda>_54}} Key: segment_ids.  Can't parse serialized Example.
	 [[{{node ParseSingleExample/ParseSingleExample}}]]
	 [[IteratorGetNext]]
0 successful operations.
0 derived errors ignored.
E0116 15:32:14.273618 140063820420928 error_handling.py:75] Error recorded from training_loop: 2 root error(s) found.
  (0) Invalid argument: {{function_node tf_data_experimental_map_and_batch_<lambda>_54}} Key: segment_ids.  Can't parse serialized Example.
	 [[{{node ParseSingleExample/ParseSingleExample}}]]
	 [[IteratorGetNext]]
	 [[IteratorGetNext/_795]]
  (1) Invalid argument: {{function_node tf_data_experimental_map_and_batch_<lambda>_54}} Key: segment_ids.  Can't parse serialized Example.
	 [[{{node ParseSingleExample/ParseSingleExample}}]]
	 [[IteratorGetNext]]
0 successful operations.
0 derived errors ignored.
INFO:tensorflow:training_loop marked as finished
I0116 15:32:14.273769 140063820420928 error_handling.py:101] training_loop marked as finished
WARNING:tensorflow:Reraising captured error
W0116 15:32:14.273835 140063820420928 error_handling.py:135] Reraising captured error
Traceback (most recent call last):
  File "/home/xxxx/anaconda3/envs/albert/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/xxxx/anaconda3/envs/albert/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/xxxx/anaconda3/envs/albert/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: {{function_node tf_data_experimental_map_and_batch_<lambda>_54}} Key: segment_ids.  Can't parse serialized Example.
	 [[{{node ParseSingleExample/ParseSingleExample}}]]
	 [[IteratorGetNext]]
	 [[IteratorGetNext/_795]]
  (1) Invalid argument: {{function_node tf_data_experimental_map_and_batch_<lambda>_54}} Key: segment_ids.  Can't parse serialized Example.
	 [[{{node ParseSingleExample/ParseSingleExample}}]]
	 [[IteratorGetNext]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_pretraining.py", line 577, in <module>
    tf.app.run()
  File "/home/xxxx/anaconda3/envs/albert/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/xxxx/.local/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/xxxx/.local/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "run_pretraining.py", line 534, in main
    estimator.train(input_fn=train_input_fn, max_steps=FLAGS.num_train_steps)
  File "/home/xxxx/anaconda3/envs/albert/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3035, in train
    rendezvous.raise_errors()
  File "/home/xxxx/anaconda3/envs/albert/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 136, in raise_errors
    six.reraise(typ, value, traceback)
  File "/home/xxxx/anaconda3/envs/albert/lib/python3.6/site-packages/six.py", line 696, in reraise
    raise value
  File "/home/xxxx/anaconda3/envs/albert/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3030, in train
    saving_listeners=saving_listeners)
  File "/home/xxxx/anaconda3/envs/albert/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 370, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/xxxx/anaconda3/envs/albert/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1161, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/xxxx/anaconda3/envs/albert/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1195, in _train_model_default
    saving_listeners)
  File "/home/xxxx/anaconda3/envs/albert/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1494, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/home/xxxx/anaconda3/envs/albert/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 754, in run
    run_metadata=run_metadata)
  File "/home/xxxx/anaconda3/envs/albert/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1259, in run
    run_metadata=run_metadata)
  File "/home/xxxx/anaconda3/envs/albert/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1360, in run
    raise six.reraise(*original_exc_info)
  File "/home/xxxx/anaconda3/envs/albert/lib/python3.6/site-packages/six.py", line 696, in reraise
    raise value
  File "/home/xxxx/anaconda3/envs/albert/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1345, in run
    return self._sess.run(*args, **kwargs)
  File "/home/xxxx/anaconda3/envs/albert/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1418, in run
    run_metadata=run_metadata)
  File "/home/xxxx/anaconda3/envs/albert/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1176, in run
    return self._sess.run(*args, **kwargs)
  File "/home/xxxx/anaconda3/envs/albert/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/xxxx/anaconda3/envs/albert/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/xxxx/anaconda3/envs/albert/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/xxxx/anaconda3/envs/albert/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: {{function_node tf_data_experimental_map_and_batch_<lambda>_54}} Key: segment_ids.  Can't parse serialized Example.
	 [[{{node ParseSingleExample/ParseSingleExample}}]]
	 [[IteratorGetNext]]
	 [[IteratorGetNext/_795]]
  (1) Invalid argument: {{function_node tf_data_experimental_map_and_batch_<lambda>_54}} Key: segment_ids.  Can't parse serialized Example.
	 [[{{node ParseSingleExample/ParseSingleExample}}]]
	 [[IteratorGetNext]]
0 successful operations.
0 derived errors ignored.

```

@LydiaXiaohongLi

**Comment by suresh96458** [comment]
@LydiaXiaohongLi 

I am also facing the same issue kindly help me in this regard

@aravindchaluvadi

**Comment by LydiaXiaohongLi** [comment]
Hi Both, sorry, when i tried on pretrain on my own mac oso having issue, I missed out that error last time. But when I try to run the pretrain step on GCP's TPU v2-8 (8 cores) using GCP's free 300 credit, it has no memory issues. And I am running on large scale, more than 100M sentence corpus, with batch size = 512, planned total training step of 1M. I will update the medium post accordingly too.

**Comment by LydiaXiaohongLi** [comment]
@aravindchaluvadi, @suresh96458, Can you please check the latest colab notebook I included in this repo, Albert_Finetune_with_Pretrain_on_Custom_Corpus_ToyModel.ipynb. Which gives E2E steps including vocab build, create pretrain files, pretrain and finetuning in the single colab notebook. Instead of using Albert's pretrain script, I have rewrite into pytorch, and since I am pretraining for less steps with small data, it can fit in CPU env for colab. As such I am closing the issue.
